/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as appAboutImport } from './routes/(app)/about'
import { Route as appUserListImport } from './routes/(app)/user/list'
import { Route as appTemplateListImport } from './routes/(app)/template/list'
import { Route as appTemplateCreateImport } from './routes/(app)/template/create'
import { Route as appRoleListImport } from './routes/(app)/role/list'
import { Route as appItemsListImport } from './routes/(app)/items/list'
import { Route as appItemsItemIdImport } from './routes/(app)/items/$itemId'
import { Route as appTemplateIdViewImport } from './routes/(app)/template/$id/view'
import { Route as appTemplateIdEditImport } from './routes/(app)/template/$id/edit'

// Create/Update Routes

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const appAboutRoute = appAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)

const appUserListRoute = appUserListImport.update({
  id: '/user/list',
  path: '/user/list',
  getParentRoute: () => appRouteRoute,
} as any)

const appTemplateListRoute = appTemplateListImport.update({
  id: '/template/list',
  path: '/template/list',
  getParentRoute: () => appRouteRoute,
} as any)

const appTemplateCreateRoute = appTemplateCreateImport.update({
  id: '/template/create',
  path: '/template/create',
  getParentRoute: () => appRouteRoute,
} as any)

const appRoleListRoute = appRoleListImport.update({
  id: '/role/list',
  path: '/role/list',
  getParentRoute: () => appRouteRoute,
} as any)

const appItemsListRoute = appItemsListImport.update({
  id: '/items/list',
  path: '/items/list',
  getParentRoute: () => appRouteRoute,
} as any)

const appItemsItemIdRoute = appItemsItemIdImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => appRouteRoute,
} as any)

const appTemplateIdViewRoute = appTemplateIdViewImport.update({
  id: '/template/$id/view',
  path: '/template/$id/view',
  getParentRoute: () => appRouteRoute,
} as any)

const appTemplateIdEditRoute = appTemplateIdEditImport.update({
  id: '/template/$id/edit',
  path: '/template/$id/edit',
  getParentRoute: () => appRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutImport
      parentRoute: typeof appRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/items/$itemId': {
      id: '/(app)/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof appItemsItemIdImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/items/list': {
      id: '/(app)/items/list'
      path: '/items/list'
      fullPath: '/items/list'
      preLoaderRoute: typeof appItemsListImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/role/list': {
      id: '/(app)/role/list'
      path: '/role/list'
      fullPath: '/role/list'
      preLoaderRoute: typeof appRoleListImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/template/create': {
      id: '/(app)/template/create'
      path: '/template/create'
      fullPath: '/template/create'
      preLoaderRoute: typeof appTemplateCreateImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/template/list': {
      id: '/(app)/template/list'
      path: '/template/list'
      fullPath: '/template/list'
      preLoaderRoute: typeof appTemplateListImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/user/list': {
      id: '/(app)/user/list'
      path: '/user/list'
      fullPath: '/user/list'
      preLoaderRoute: typeof appUserListImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/template/$id/edit': {
      id: '/(app)/template/$id/edit'
      path: '/template/$id/edit'
      fullPath: '/template/$id/edit'
      preLoaderRoute: typeof appTemplateIdEditImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/template/$id/view': {
      id: '/(app)/template/$id/view'
      path: '/template/$id/view'
      fullPath: '/template/$id/view'
      preLoaderRoute: typeof appTemplateIdViewImport
      parentRoute: typeof appRouteImport
    }
  }
}

// Create and export the route tree

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appIndexRoute: typeof appIndexRoute
  appItemsItemIdRoute: typeof appItemsItemIdRoute
  appItemsListRoute: typeof appItemsListRoute
  appRoleListRoute: typeof appRoleListRoute
  appTemplateCreateRoute: typeof appTemplateCreateRoute
  appTemplateListRoute: typeof appTemplateListRoute
  appUserListRoute: typeof appUserListRoute
  appTemplateIdEditRoute: typeof appTemplateIdEditRoute
  appTemplateIdViewRoute: typeof appTemplateIdViewRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appIndexRoute: appIndexRoute,
  appItemsItemIdRoute: appItemsItemIdRoute,
  appItemsListRoute: appItemsListRoute,
  appRoleListRoute: appRoleListRoute,
  appTemplateCreateRoute: appTemplateCreateRoute,
  appTemplateListRoute: appTemplateListRoute,
  appUserListRoute: appUserListRoute,
  appTemplateIdEditRoute: appTemplateIdEditRoute,
  appTemplateIdViewRoute: appTemplateIdViewRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/about': typeof appAboutRoute
  '/login': typeof authLoginRoute
  '/items/$itemId': typeof appItemsItemIdRoute
  '/items/list': typeof appItemsListRoute
  '/role/list': typeof appRoleListRoute
  '/template/create': typeof appTemplateCreateRoute
  '/template/list': typeof appTemplateListRoute
  '/user/list': typeof appUserListRoute
  '/template/$id/edit': typeof appTemplateIdEditRoute
  '/template/$id/view': typeof appTemplateIdViewRoute
}

export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/items/$itemId': typeof appItemsItemIdRoute
  '/items/list': typeof appItemsListRoute
  '/role/list': typeof appRoleListRoute
  '/template/create': typeof appTemplateCreateRoute
  '/template/list': typeof appTemplateListRoute
  '/user/list': typeof appUserListRoute
  '/template/$id/edit': typeof appTemplateIdEditRoute
  '/template/$id/view': typeof appTemplateIdViewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/items/$itemId': typeof appItemsItemIdRoute
  '/(app)/items/list': typeof appItemsListRoute
  '/(app)/role/list': typeof appRoleListRoute
  '/(app)/template/create': typeof appTemplateCreateRoute
  '/(app)/template/list': typeof appTemplateListRoute
  '/(app)/user/list': typeof appUserListRoute
  '/(app)/template/$id/edit': typeof appTemplateIdEditRoute
  '/(app)/template/$id/view': typeof appTemplateIdViewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/items/$itemId'
    | '/items/list'
    | '/role/list'
    | '/template/create'
    | '/template/list'
    | '/user/list'
    | '/template/$id/edit'
    | '/template/$id/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/'
    | '/items/$itemId'
    | '/items/list'
    | '/role/list'
    | '/template/create'
    | '/template/list'
    | '/user/list'
    | '/template/$id/edit'
    | '/template/$id/view'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/about'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/items/$itemId'
    | '/(app)/items/list'
    | '/(app)/role/list'
    | '/(app)/template/create'
    | '/(app)/template/list'
    | '/(app)/user/list'
    | '/(app)/template/$id/edit'
    | '/(app)/template/$id/view'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/(auth)/login"
      ]
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/about",
        "/(app)/",
        "/(app)/items/$itemId",
        "/(app)/items/list",
        "/(app)/role/list",
        "/(app)/template/create",
        "/(app)/template/list",
        "/(app)/user/list",
        "/(app)/template/$id/edit",
        "/(app)/template/$id/view"
      ]
    },
    "/(app)/about": {
      "filePath": "(app)/about.tsx",
      "parent": "/(app)"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/items/$itemId": {
      "filePath": "(app)/items/$itemId.tsx",
      "parent": "/(app)"
    },
    "/(app)/items/list": {
      "filePath": "(app)/items/list.tsx",
      "parent": "/(app)"
    },
    "/(app)/role/list": {
      "filePath": "(app)/role/list.tsx",
      "parent": "/(app)"
    },
    "/(app)/template/create": {
      "filePath": "(app)/template/create.tsx",
      "parent": "/(app)"
    },
    "/(app)/template/list": {
      "filePath": "(app)/template/list.tsx",
      "parent": "/(app)"
    },
    "/(app)/user/list": {
      "filePath": "(app)/user/list.tsx",
      "parent": "/(app)"
    },
    "/(app)/template/$id/edit": {
      "filePath": "(app)/template/$id/edit.tsx",
      "parent": "/(app)"
    },
    "/(app)/template/$id/view": {
      "filePath": "(app)/template/$id/view.tsx",
      "parent": "/(app)"
    }
  }
}
ROUTE_MANIFEST_END */
