/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as appRouteImport } from './routes/(app)/route'
import { Route as appIndexImport } from './routes/(app)/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as appAboutImport } from './routes/(app)/about'
import { Route as appUserListImport } from './routes/(app)/user/list'
import { Route as appRoleListImport } from './routes/(app)/role/list'

// Create/Update Routes

const appRouteRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const appIndexRoute = appIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const appAboutRoute = appAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appRouteRoute,
} as any)

const appUserListRoute = appUserListImport.update({
  id: '/user/list',
  path: '/user/list',
  getParentRoute: () => appRouteRoute,
} as any)

const appRoleListRoute = appRoleListImport.update({
  id: '/role/list',
  path: '/role/list',
  getParentRoute: () => appRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/about': {
      id: '/(app)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appAboutImport
      parentRoute: typeof appRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/role/list': {
      id: '/(app)/role/list'
      path: '/role/list'
      fullPath: '/role/list'
      preLoaderRoute: typeof appRoleListImport
      parentRoute: typeof appRouteImport
    }
    '/(app)/user/list': {
      id: '/(app)/user/list'
      path: '/user/list'
      fullPath: '/user/list'
      preLoaderRoute: typeof appUserListImport
      parentRoute: typeof appRouteImport
    }
  }
}

// Create and export the route tree

interface appRouteRouteChildren {
  appAboutRoute: typeof appAboutRoute
  appIndexRoute: typeof appIndexRoute
  appRoleListRoute: typeof appRoleListRoute
  appUserListRoute: typeof appUserListRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAboutRoute: appAboutRoute,
  appIndexRoute: appIndexRoute,
  appRoleListRoute: appRoleListRoute,
  appUserListRoute: appUserListRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/about': typeof appAboutRoute
  '/login': typeof authLoginRoute
  '/role/list': typeof appRoleListRoute
  '/user/list': typeof appUserListRoute
}

export interface FileRoutesByTo {
  '/about': typeof appAboutRoute
  '/login': typeof authLoginRoute
  '/': typeof appIndexRoute
  '/role/list': typeof appRoleListRoute
  '/user/list': typeof appUserListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/about': typeof appAboutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/role/list': typeof appRoleListRoute
  '/(app)/user/list': typeof appUserListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/login' | '/role/list' | '/user/list'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/' | '/role/list' | '/user/list'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/about'
    | '/(auth)/login'
    | '/(app)/'
    | '/(app)/role/list'
    | '/(app)/user/list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(app)",
        "/(auth)/login"
      ]
    },
    "/(app)": {
      "filePath": "(app)/route.tsx",
      "children": [
        "/(app)/about",
        "/(app)/",
        "/(app)/role/list",
        "/(app)/user/list"
      ]
    },
    "/(app)/about": {
      "filePath": "(app)/about.tsx",
      "parent": "/(app)"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(app)/": {
      "filePath": "(app)/index.tsx",
      "parent": "/(app)"
    },
    "/(app)/role/list": {
      "filePath": "(app)/role/list.tsx",
      "parent": "/(app)"
    },
    "/(app)/user/list": {
      "filePath": "(app)/user/list.tsx",
      "parent": "/(app)"
    }
  }
}
ROUTE_MANIFEST_END */
